/* ============================================================
   DGT · Фразы и формулировки из билетов
   Два типа карточек:
     type:'collocation' — словосочетание-«кирпичик»
     type:'sentence'    — целая экзаменационная формулировка
   Группы (g) дают цветовую навигацию и фильтрацию.
   ============================================================ */

const GROUPS = {
  speed:   {name:'Скорость и дистанция', color:'#0a4ea3'},
  light:   {name:'Свет и видимость',     color:'#e2a400'},
  overtake:{name:'Обгон и манёвр',       color:'#c8102e'},
  belt:    {name:'Ремень и пассивная безопасность', color:'#1c7c43'},
  driver:  {name:'Состояние водителя',   color:'#6b4fa0'},
  vehicle: {name:'ТС, шины, груз',       color:'#0e7c86'},
  rules:   {name:'Правила и обстановка',  color:'#7a5c3e'}
};

/* --- СЛОВОСОЧЕТАНИЯ (collocations) --- */
const COLLOCATIONS = [
  // Скорость и дистанция
  {en:'minimum speed limit',          ru:'минимальная разрешённая скорость',           h:'minimum = минимум',           g:'speed'},
  {en:'to comply with',               ru:'соблюдать (правило, ограничение)',           h:'комплаенс — соблюдение норм',  g:'speed'},
  {en:'abnormally low speed',         ru:'аномально низкая скорость',                  h:'аномальный — ненормальный',    g:'speed'},
  {en:'safety distance',              ru:'безопасная дистанция',                       h:'safety = безопасность',        g:'speed'},
  {en:'braking distance',             ru:'тормозной путь',                             h:'brake = тормоз',               g:'speed'},
  {en:'the vehicle in front',         ru:'впереди идущее ТС',                          h:'in front = впереди',           g:'speed'},
  {en:'to stop in time',              ru:'успеть остановиться вовремя',                h:'in time = вовремя',            g:'speed'},
  {en:'inappropriate speed',          ru:'несоответствующая скорость',                 h:'in- = не: неподходящая',       g:'speed'},
  {en:'reaction time',                ru:'время реакции',                              h:'реакция — отклик',             g:'speed'},
  {en:'reduced speed',                ru:'пониженная скорость',                        h:'редуктор снижает',             g:'speed'},

  // Свет и видимость
  {en:'front fog light',              ru:'передняя противотуманная фара',              h:'fog = туман',                  g:'light'},
  {en:'rear fog light',               ru:'задняя противотуманная фара',                h:'rear = задний',                g:'light'},
  {en:'low beam / dipped beam',       ru:'ближний свет',                               h:'dipped = опущенный луч',       g:'light'},
  {en:'high beam / main beam',        ru:'дальний свет',                               h:'main = основной, большой',     g:'light'},
  {en:'position light',               ru:'габаритный огонь',                           h:'position = положение ТС',      g:'light'},
  {en:'parking light',                ru:'стояночный огонь',                           h:'parking = стоянка',            g:'light'},
  {en:'nighttime glare',              ru:'ослепление ночью',                           h:'glare = слепящий блик',        g:'light'},
  {en:'to raise the beam',            ru:'поднять луч (фары)',                          h:'raise = поднимать',            g:'light'},
  {en:'to reduce visibility',         ru:'снижать видимость',                          h:'visible = видимый',            g:'light'},
  {en:'insufficiently lit road',      ru:'недостаточно освещённая дорога',             h:'lit = освещён (light)',        g:'light'},
  {en:'between sunset and sunrise',   ru:'между закатом и рассветом',                  h:'sunset/sunrise — закат/рассвет', g:'light'},
  {en:'built-up area',                ru:'населённый пункт, застройка',                h:'built up = застроено',         g:'light'},

  // Обгон и манёвр
  {en:'to overtake',                  ru:'обгонять',                                   h:'over + take — «брать сверху»', g:'overtake'},
  {en:'the blind spot',               ru:'слепая зона',                                h:'blind = слепой, spot = точка', g:'overtake'},
  {en:'oncoming traffic',             ru:'встречное движение',                         h:'on-coming — «идущее на тебя»', g:'overtake'},
  {en:'the lane reserved for...',     ru:'полоса, отведённая для...',                  h:'reserved = зарезервирована',   g:'overtake'},
  {en:'without leaving your lane',    ru:'не покидая своей полосы',                    h:'leave = покидать, lane = полоса', g:'overtake'},
  {en:'pedestrian crossing',          ru:'пешеходный переход',                         h:'pedestrian = пешеход',         g:'overtake'},
  {en:'right of way',                 ru:'право проезда, преимущество',                h:'right = право, way = путь',    g:'overtake'},
  {en:'the vehicle travelling uphill',ru:'ТС, движущееся в гору',                      h:'up + hill — «вверх по холму»', g:'overtake'},
  {en:'the vehicle travelling downhill',ru:'ТС, движущееся под гору',                  h:'down + hill — «вниз»',         g:'overtake'},
  {en:'steep section of road',        ru:'крутой участок дороги',                      h:'steep = крутой склон',         g:'overtake'},
  {en:'to pass each other',           ru:'разъехаться (встречным)',                    h:'pass = проходить мимо',        g:'overtake'},

  // Ремень и пассивная безопасность
  {en:'seat belt',                    ru:'ремень безопасности',                        h:'seat = сиденье, belt = ремень', g:'belt'},
  {en:'seat belt straps',             ru:'лямки ремня',                                h:'strap = лямка, ремешок',       g:'belt'},
  {en:'properly adjusted',            ru:'правильно отрегулирован',                    h:'adjust = настроить',           g:'belt'},
  {en:'loose despite being fastened', ru:'провисает, хотя застёгнут',                  h:'loose = слабый, fasten = застегнуть', g:'belt'},
  {en:'to lose effectiveness',        ru:'терять эффективность',                       h:'effective = действенный',      g:'belt'},
  {en:'to stabilize the occupant',    ru:'фиксировать сидящего',                       h:'occupant = пассажир/водитель', g:'belt'},
  {en:'the headrest',                 ru:'подголовник',                                h:'head + rest — «опора головы»', g:'belt'},
  {en:'the cervical spine',           ru:'шейный отдел позвоночника',                  h:'цервикальный — шейный',        g:'belt'},
  {en:'in the event of an accident',  ru:'в случае ДТП',                               h:'event = случай, accident = авария', g:'belt'},
  {en:'to hit the steering wheel',    ru:'удариться о руль',                           h:'steering wheel — рулевое колесо', g:'belt'},
  {en:'to be mandatory',              ru:'быть обязательным',                          h:'мандат — обязательное',        g:'belt'},

  // Состояние водителя
  {en:'the onset of fatigue',         ru:'наступление усталости',                      h:'onset = начало, fatigue = усталость', g:'driver'},
  {en:'the onset of drowsiness',      ru:'наступление сонливости',                     h:'drowsy = сонный',              g:'driver'},
  {en:'adverse weather conditions',   ru:'неблагоприятные погодные условия',           h:'adverse = неблагоприятный',    g:'driver'},
  {en:'deterioration of abilities',   ru:'ухудшение способностей',                     h:'деградация — ухудшение',       g:'driver'},
  {en:'reduced attention capacity',   ru:'сниженная способность концентрации',         h:'attention = внимание',         g:'driver'},
  {en:'slower reaction times',        ru:'замедленная реакция',                        h:'slow = медленный',             g:'driver'},
  {en:'to suffer from depression',    ru:'страдать депрессией',                        h:'suffer = страдать',            g:'driver'},
  {en:'insecure when making decisions',ru:'неуверенный при принятии решений',          h:'secure = уверенный/защищённый', g:'driver'},
  {en:'to take a break / to rest',    ru:'сделать перерыв / отдохнуть',                h:'break = перерыв',              g:'driver'},
  {en:'changing sleep schedules',     ru:'сбой режима сна',                            h:'schedule = расписание',        g:'driver'},
  {en:'under the influence of alcohol',ru:'в состоянии опьянения',                     h:'influence = влияние',          g:'driver'},
  {en:'blood alcohol level',          ru:'уровень алкоголя в крови',                   h:'blood = кровь',                g:'driver'},
  {en:'a novice driver',              ru:'начинающий водитель',                        h:'новичок — novice',             g:'driver'},
  {en:'milligrams per liter of exhaled air',ru:'мг на литр выдыхаемого воздуха',       h:'exhale = выдыхать',            g:'driver'},

  // ТС, шины, груз
  {en:'a rim',                        ru:'обод колеса, диск',                          h:'обод = край колеса',           g:'vehicle'},
  {en:'smooth surface on its edges',  ru:'гладкая поверхность по краям',               h:'smooth = гладкий, edge = край', g:'vehicle'},
  {en:'deformation on its edges',     ru:'деформация по краям',                        h:'деформация — искривление',     g:'vehicle'},
  {en:'signs of corrosion',           ru:'следы коррозии',                             h:'коррозия — ржавчина',          g:'vehicle'},
  {en:'the charging circuit',         ru:'цепь зарядки',                               h:'charge = заряд, circuit = цепь', g:'vehicle'},
  {en:'direct current',               ru:'постоянный ток',                             h:'direct = прямой',              g:'vehicle'},
  {en:'alternating current',          ru:'переменный ток',                             h:'alternate = чередоваться',     g:'vehicle'},
  {en:'the load protrudes',           ru:'груз выступает',                             h:'protrude = торчать, выступать', g:'vehicle'},
  {en:'protrudes at the rear / front',ru:'выступает сзади / спереди',                  h:'rear = зад, front = перёд',    g:'vehicle'},
  {en:'maximum width / length',       ru:'максимальная ширина / длина',                h:'width = ширина, length = длина', g:'vehicle'},
  {en:'a pothole in the roadway',     ru:'яма на проезжей части',                      h:'pot + hole — «яма-котёл»',     g:'vehicle'},
  {en:'to keep the motorcycle upright',ru:'держать мотоцикл вертикально',              h:'upright = прямо, вертикально', g:'vehicle'},

  // Правила и обстановка
  {en:'lower limits are advisory',    ru:'нижние пределы носят рекомендательный характер',h:'advisory = совещательный',  g:'rules'},
  {en:'to be penalized',              ru:'быть оштрафованным',                         h:'пенальти — наказание',         g:'rules'},
  {en:'to mark an obstacle',          ru:'обозначить препятствие',                     h:'mark = метить, obstacle = препятствие', g:'rules'},
  {en:'to hinder traffic',            ru:'мешать движению',                            h:'hinder = препятствовать',      g:'rules'},
  {en:'personal mobility vehicle',    ru:'средство индивидуальной мобильности',        h:'mobility = подвижность',       g:'rules'},
  {en:'to be towed',                  ru:'быть на буксире',                            h:'tow = буксировать',            g:'rules'},
  {en:'immobilization of a vehicle',  ru:'задержание/обездвиживание ТС',               h:'иммобилайзер обездвиживает',   g:'rules'},
  {en:'a law enforcement officer',    ru:'сотрудник правопорядка',                     h:'enforce = принуждать к исполнению', g:'rules'},
  {en:'the reasons no longer exist',  ru:'причины более не существуют',                h:'no longer = более не',         g:'rules'},
  {en:'to be exempt',                 ru:'быть освобождённым (от обязанности)',        h:'экземпляр изъят',              g:'rules'},
  {en:'in pedestrian areas',          ru:'в пешеходных зонах',                         h:'area = зона',                  g:'rules'},
  {en:'distractions of the cyclists', ru:'отвлечение самих велосипедистов',            h:'cyclist = велосипедист',       g:'rules'}
];

/* --- ЦЕЛЫЕ ФОРМУЛИРОВКИ (sentences) --- */
const SENTENCES = [
  {en:'Is it important to comply with minimum speed limits?',
   ru:'Важно ли соблюдать минимальную разрешённую скорость?',
   h:'Ответ: да, чтобы не создавать аварийных ситуаций', g:'speed'},
  {en:'In foggy conditions, is it advisable to increase the safety distance?',
   ru:'В тумане целесообразно ли увеличить безопасную дистанцию?',
   h:'Ответ: да, чтобы снизить риск ДТП', g:'speed'},
  {en:'Among the most frequent causes of traffic accidents is driving at an inappropriate speed.',
   ru:'Одна из частых причин ДТП — движение с несоответствующей скоростью.',
   h:'inappropriate, не appropriate', g:'speed'},

  {en:'When may the front fog light be used?',
   ru:'Когда можно использовать переднюю противотуманную фару?',
   h:'Когда условия резко снижают видимость', g:'light'},
  {en:'Which action causes nighttime glare?',
   ru:'Какое действие вызывает ослепление ночью?',
   h:'Поднятие луча дальнего/ближнего света', g:'light'},
  {en:'Together with which light must the low beam always operate?',
   ru:'С каким светом всегда должен работать ближний свет?',
   h:'С габаритными огнями (position light)', g:'light'},
  {en:'When is a road considered to be insufficiently lit?',
   ru:'Когда дорога считается недостаточно освещённой?',
   h:'Когда номер впереди не читается со 100 м… (по билету — 10 м)', g:'light'},
  {en:'What conditions must a vehicle meet to use parking lights?',
   ru:'Каким условиям должно отвечать ТС, чтобы использовать стояночные огни?',
   h:'Ширина до 2 м и длина до 6 м', g:'light'},

  {en:'What must we be particularly careful with when overtaking on a motorway?',
   ru:'На что особенно обращать внимание при обгоне на автомагистрали?',
   h:'На слепую зону (the blind spot)', g:'overtake'},
  {en:'From the sign onwards, is it permitted to overtake a motorcycle?',
   ru:'Разрешён ли с этого знака обгон мотоцикла?',
   h:'Да, если не выезжаешь на встречную полосу', g:'overtake'},
  {en:'At pedestrian crossings, is overtaking allowed?',
   ru:'Разрешён ли обгон на пешеходных переходах?',
   h:'Нет, никогда', g:'overtake'},
  {en:'On a steep section, which vehicle has right of way?',
   ru:'На крутом участке у какого ТС преимущество?',
   h:'У движущегося в гору (uphill)', g:'overtake'},

  {en:'When the seat belt straps are not properly adjusted, the belt will be less effective.',
   ru:'Если лямки ремня плохо отрегулированы, ремень менее эффективен.',
   h:'…и может причинить травмы при ДТП', g:'belt'},
  {en:'Does a pregnant woman have to wear a seat belt?',
   ru:'Обязана ли беременная женщина пристёгиваться?',
   h:'Да, это обязательно для всех', g:'belt'},
  {en:'The headrest’s main purpose is to protect the cervical spine.',
   ru:'Главное назначение подголовника — защита шейного отдела позвоночника.',
   h:'Ограничивает резкое движение головы назад', g:'belt'},
  {en:'When the seat belt is loose despite being fastened, you will travel further and may hit the wheel.',
   ru:'Если ремень провисает, хотя застёгнут, тело сместится дальше и ударится о руль.',
   h:'loose = провисает', g:'belt'},

  {en:'Which environmental circumstances encourage the onset of fatigue?',
   ru:'Какие внешние условия способствуют наступлению усталости?',
   h:'Неблагоприятная погода (adverse weather)', g:'driver'},
  {en:'Elderly people tend to have a deterioration of abilities that affects driving.',
   ru:'У пожилых людей способности ухудшаются, что влияет на вождение.',
   h:'deterioration = ухудшение', g:'driver'},
  {en:'What attitude do drivers who suffer from depression adopt?',
   ru:'Как ведут себя водители, страдающие депрессией?',
   h:'Более неуверенно при принятии решений', g:'driver'},
  {en:'Driving for a long time without a break encourages the onset of fatigue.',
   ru:'Долгое вождение без перерыва способствует наступлению усталости.',
   h:'onset of fatigue', g:'driver'},
  {en:'To reduce drowsiness, rest at least 20 minutes every 2 hours or 200 km.',
   ru:'Чтобы снизить сонливость, отдыхайте не менее 20 минут каждые 2 часа или 200 км.',
   h:'20 минут / 2 часа / 200 км', g:'driver'},
  {en:'Does alcohol produce the same effects in all people?',
   ru:'Одинаково ли алкоголь действует на всех людей?',
   h:'Нет — зависит от веса, пола, состояния', g:'driver'},
  {en:'What is the maximum permitted blood alcohol level for a novice driver?',
   ru:'Каков максимально допустимый уровень алкоголя для начинающего водителя?',
   h:'0,15 мг/л выдыхаемого воздуха', g:'driver'},
  {en:'Who is more vulnerable to the effects of alcohol?',
   ru:'Кто более уязвим к действию алкоголя?',
   h:'Лица младше 18 и старше 65 лет', g:'driver'},

  {en:'Which characteristics must a rim have to work properly?',
   ru:'Какими свойствами должен обладать диск, чтобы работать исправно?',
   h:'Гладкая поверхность по краям (smooth surface)', g:'vehicle'},
  {en:'Which part of the charging circuit produces direct current?',
   ru:'Какая часть цепи зарядки вырабатывает постоянный ток?',
   h:'Динамо (dynamo), а не генератор', g:'vehicle'},
  {en:'The load protrudes from the vehicle. Is it mandatory to mark it?',
   ru:'Груз выступает из ТС. Обязательно ли его обозначать?',
   h:'Да, для груза, выступающего сзади', g:'vehicle'},
  {en:'If you cannot avoid a pothole, what is the most appropriate action?',
   ru:'Если яму не объехать, какое действие наиболее правильное?',
   h:'Снизить скорость и держать мотоцикл прямо', g:'vehicle'},

  {en:'Is it advisable to drive while wearing a bulky coat?',
   ru:'Целесообразно ли вести машину в объёмной куртке?',
   h:'Нет — снижает эффективность ремня', g:'belt'},
  {en:'Must we mark obstacles left on the road that hinder traffic?',
   ru:'Нужно ли обозначать оставленные на дороге препятствия, мешающие движению?',
   h:'Да, всегда, в любое время суток', g:'rules'},
  {en:'Users of personal mobility vehicles may not be towed by other vehicles.',
   ru:'Средства индивидуальной мобильности нельзя буксировать другими ТС.',
   h:'may not be towed', g:'rules'},
  {en:'When will the immobilization ordered by an officer be lifted?',
   ru:'Когда снимут задержание ТС, наложенное сотрудником?',
   h:'Как только исчезнут причины, его вызвавшие', g:'rules'},
  {en:'Do distractions have an influence on accidents involving cyclists?',
   ru:'Влияет ли отвлечение на аварии с участием велосипедистов?',
   h:'Да, отвлечение самих велосипедистов', g:'rules'},
  {en:'How should you drive uphill when there is snow on the road?',
   ru:'Как ехать в гору, когда на дороге снег?',
   h:'Медленно и с постоянной скоростью', g:'rules'}
];
